/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateFolderData model module.
 * @module model/CreateFolderData
 * @version 2.1.0
 */
class CreateFolderData {
    /**
     * Constructs a new <code>CreateFolderData</code>.
     * @alias module:model/CreateFolderData
     * @param folder {Object} 
     */
    constructor(folder) { 
        
        CreateFolderData.initialize(this, folder);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, folder) { 
        obj['folder'] = folder;
    }

    /**
     * Constructs a <code>CreateFolderData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFolderData} obj Optional instance to populate.
     * @return {module:model/CreateFolderData} The populated <code>CreateFolderData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFolderData();

            if (data.hasOwnProperty('folder')) {
                obj['folder'] = ApiClient.convertToType(data['folder'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateFolderData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateFolderData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateFolderData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

CreateFolderData.RequiredProperties = ["folder"];

/**
 * @member {Object} folder
 */
CreateFolderData.prototype['folder'] = undefined;






export default CreateFolderData;

