/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MoveTemplateData model module.
 * @module model/MoveTemplateData
 * @version 2.0.0
 */
class MoveTemplateData {
    /**
     * Constructs a new <code>MoveTemplateData</code>.
     * @alias module:model/MoveTemplateData
     * @param parentFolderId {String} 
     */
    constructor(parentFolderId) { 
        
        MoveTemplateData.initialize(this, parentFolderId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, parentFolderId) { 
        obj['parent_folder_id'] = parentFolderId;
    }

    /**
     * Constructs a <code>MoveTemplateData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MoveTemplateData} obj Optional instance to populate.
     * @return {module:model/MoveTemplateData} The populated <code>MoveTemplateData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MoveTemplateData();

            if (data.hasOwnProperty('parent_folder_id')) {
                obj['parent_folder_id'] = ApiClient.convertToType(data['parent_folder_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MoveTemplateData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MoveTemplateData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MoveTemplateData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['parent_folder_id'] && !(typeof data['parent_folder_id'] === 'string' || data['parent_folder_id'] instanceof String)) {
            throw new Error("Expected the field `parent_folder_id` to be a primitive type in the JSON string but got " + data['parent_folder_id']);
        }

        return true;
    }


}

MoveTemplateData.RequiredProperties = ["parent_folder_id"];

/**
 * @member {String} parent_folder_id
 */
MoveTemplateData.prototype['parent_folder_id'] = undefined;






export default MoveTemplateData;

