/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MultipleErrorsResponse model module.
 * @module model/MultipleErrorsResponse
 * @version 2.0.0
 */
class MultipleErrorsResponse {
    /**
     * Constructs a new <code>MultipleErrorsResponse</code>.
     * @alias module:model/MultipleErrorsResponse
     * @param status {module:model/MultipleErrorsResponse.StatusEnum} 
     * @param errors {Array.<String>} 
     */
    constructor(status, errors) { 
        
        MultipleErrorsResponse.initialize(this, status, errors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, errors) { 
        obj['status'] = status;
        obj['errors'] = errors;
    }

    /**
     * Constructs a <code>MultipleErrorsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultipleErrorsResponse} obj Optional instance to populate.
     * @return {module:model/MultipleErrorsResponse} The populated <code>MultipleErrorsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultipleErrorsResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MultipleErrorsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MultipleErrorsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MultipleErrorsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['errors'])) {
            throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
        }

        return true;
    }


}

MultipleErrorsResponse.RequiredProperties = ["status", "errors"];

/**
 * @member {module:model/MultipleErrorsResponse.StatusEnum} status
 */
MultipleErrorsResponse.prototype['status'] = undefined;

/**
 * @member {Array.<String>} errors
 */
MultipleErrorsResponse.prototype['errors'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
MultipleErrorsResponse['StatusEnum'] = {

    /**
     * value: "error"
     * @const
     */
    "error": "error"
};



export default MultipleErrorsResponse;

