/**
 * DocSpring API
 * Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubmissionPreview from './SubmissionPreview';

/**
 * The Submission422Response model module.
 * @module model/Submission422Response
 * @version 3.0.0
 */
class Submission422Response {
    /**
     * Constructs a new <code>Submission422Response</code>.
     * @alias module:model/Submission422Response
     * @param status {module:model/Submission422Response.StatusEnum} 
     */
    constructor(status) { 
        
        Submission422Response.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>Submission422Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Submission422Response} obj Optional instance to populate.
     * @return {module:model/Submission422Response} The populated <code>Submission422Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Submission422Response();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('submission')) {
                obj['submission'] = SubmissionPreview.constructFromObject(data['submission']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Submission422Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Submission422Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Submission422Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // validate the optional field `submission`
        if (data['submission']) { // data not null
          SubmissionPreview.validateJSON(data['submission']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['errors'])) {
            throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
        }

        return true;
    }


}

Submission422Response.RequiredProperties = ["status"];

/**
 * @member {module:model/Submission422Response.StatusEnum} status
 */
Submission422Response.prototype['status'] = undefined;

/**
 * Single error message (for non-validation errors)
 * @member {String} error
 */
Submission422Response.prototype['error'] = undefined;

/**
 * @member {module:model/SubmissionPreview} submission
 */
Submission422Response.prototype['submission'] = undefined;

/**
 * Array of validation error messages (when submission data is invalid)
 * @member {Array.<String>} errors
 */
Submission422Response.prototype['errors'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Submission422Response['StatusEnum'] = {

    /**
     * value: "error"
     * @const
     */
    "error": "error"
};



export default Submission422Response;

