/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/TemplateData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TemplateData'));
  } else {
    // Browser globals (root is window)
    if (!root.DocSpring) {
      root.DocSpring = {};
    }
    root.DocSpring.UpdateTemplateData = factory(root.DocSpring.ApiClient, root.DocSpring.TemplateData);
  }
}(this, function(ApiClient, TemplateData) {
  'use strict';




  /**
   * The UpdateTemplateData model module.
   * @module model/UpdateTemplateData
   * @version 1.4.0
   */

  /**
   * Constructs a new <code>UpdateTemplateData</code>.
   * @alias module:model/UpdateTemplateData
   * @class
   * @param template {module:model/TemplateData} 
   */
  var exports = function(template) {
    var _this = this;

    _this['template'] = template;
  };

  /**
   * Constructs a <code>UpdateTemplateData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateTemplateData} obj Optional instance to populate.
   * @return {module:model/UpdateTemplateData} The populated <code>UpdateTemplateData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('template')) {
        obj['template'] = TemplateData.constructFromObject(data['template']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/TemplateData} template
   */
  exports.prototype['template'] = undefined;



  return exports;
}));


