/**
 * DocSpring API
 * Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocSpring);
  }
}(this, function(expect, DocSpring) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocSpring.CombinedSubmission();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CombinedSubmission', function() {
    it('should create an instance of CombinedSubmission', function() {
      // uncomment below and update the code to test CombinedSubmission
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be.a(DocSpring.CombinedSubmission);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property expired (base name: "expired")', function() {
      // uncomment below and update the code to test the property expired
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property expires_in (base name: "expires_in")', function() {
      // uncomment below and update the code to test the property expires_in
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property expires_at (base name: "expires_at")', function() {
      // uncomment below and update the code to test the property expires_at
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property processed_at (base name: "processed_at")', function() {
      // uncomment below and update the code to test the property processed_at
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property error_message (base name: "error_message")', function() {
      // uncomment below and update the code to test the property error_message
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property submission_ids (base name: "submission_ids")', function() {
      // uncomment below and update the code to test the property submission_ids
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property source_pdfs (base name: "source_pdfs")', function() {
      // uncomment below and update the code to test the property source_pdfs
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property pdf_hash (base name: "pdf_hash")', function() {
      // uncomment below and update the code to test the property pdf_hash
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property download_url (base name: "download_url")', function() {
      // uncomment below and update the code to test the property download_url
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

    it('should have the property actions (base name: "actions")', function() {
      // uncomment below and update the code to test the property actions
      //var instance = new DocSpring.CombinedSubmission();
      //expect(instance).to.be();
    });

  });

}));
