/**
 * DocSpring API
 * Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocSpring);
  }
}(this, function(expect, DocSpring) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocSpring.CreateSubmissionDataRequestResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateSubmissionDataRequestResponse', function() {
    it('should create an instance of CreateSubmissionDataRequestResponse', function() {
      // uncomment below and update the code to test CreateSubmissionDataRequestResponse
      //var instance = new DocSpring.CreateSubmissionDataRequestResponse();
      //expect(instance).to.be.a(DocSpring.CreateSubmissionDataRequestResponse);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new DocSpring.CreateSubmissionDataRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property data_request (base name: "data_request")', function() {
      // uncomment below and update the code to test the property data_request
      //var instance = new DocSpring.CreateSubmissionDataRequestResponse();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instance = new DocSpring.CreateSubmissionDataRequestResponse();
      //expect(instance).to.be();
    });

  });

}));
