/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocSpring);
  }
}(this, function(expect, DocSpring) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocSpring.SubmissionDataRequestEvent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubmissionDataRequestEvent', function() {
    it('should create an instance of SubmissionDataRequestEvent', function() {
      // uncomment below and update the code to test SubmissionDataRequestEvent
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be.a(DocSpring.SubmissionDataRequestEvent);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property submissionId (base name: "submission_id")', function() {
      // uncomment below and update the code to test the property submissionId
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property submissionDataRequestId (base name: "submission_data_request_id")', function() {
      // uncomment below and update the code to test the property submissionDataRequestId
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "event_type")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property messageType (base name: "message_type")', function() {
      // uncomment below and update the code to test the property messageType
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property messageRecipient (base name: "message_recipient")', function() {
      // uncomment below and update the code to test the property messageRecipient
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

    it('should have the property occurredAt (base name: "occurred_at")', function() {
      // uncomment below and update the code to test the property occurredAt
      //var instance = new DocSpring.SubmissionDataRequestEvent();
      //expect(instance).to.be();
    });

  });

}));
