/**
 * DocSpring API
 * Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocSpring);
  }
}(this, function(expect, DocSpring) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocSpring.SubmissionAction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubmissionAction', function() {
    it('should create an instance of SubmissionAction', function() {
      // uncomment below and update the code to test SubmissionAction
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be.a(DocSpring.SubmissionAction);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

    it('should have the property integration_id (base name: "integration_id")', function() {
      // uncomment below and update the code to test the property integration_id
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

    it('should have the property action_type (base name: "action_type")', function() {
      // uncomment below and update the code to test the property action_type
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

    it('should have the property action_category (base name: "action_category")', function() {
      // uncomment below and update the code to test the property action_category
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

    it('should have the property result_data (base name: "result_data")', function() {
      // uncomment below and update the code to test the property result_data
      //var instance = new DocSpring.SubmissionAction();
      //expect(instance).to.be();
    });

  });

}));
