/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocSpring);
  }
}(this, function(expect, DocSpring) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocSpring.TemplatePreview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplatePreview', function() {
    it('should create an instance of TemplatePreview', function() {
      // uncomment below and update the code to test TemplatePreview
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be.a(DocSpring.TemplatePreview);
    });

    it('should have the property addDataRequestSubmissionIdFooters (base name: "add_data_request_submission_id_footers")', function() {
      // uncomment below and update the code to test the property addDataRequestSubmissionIdFooters
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property allowAdditionalProperties (base name: "allow_additional_properties")', function() {
      // uncomment below and update the code to test the property allowAdditionalProperties
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentFilename (base name: "document_filename")', function() {
      // uncomment below and update the code to test the property documentFilename
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentMd5 (base name: "document_md5")', function() {
      // uncomment below and update the code to test the property documentMd5
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentParseError (base name: "document_parse_error")', function() {
      // uncomment below and update the code to test the property documentParseError
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentProcessed (base name: "document_processed")', function() {
      // uncomment below and update the code to test the property documentProcessed
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentState (base name: "document_state")', function() {
      // uncomment below and update the code to test the property documentState
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property documentUrl (base name: "document_url")', function() {
      // uncomment below and update the code to test the property documentUrl
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property editableSubmissions (base name: "editable_submissions")', function() {
      // uncomment below and update the code to test the property editableSubmissions
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property embedDomains (base name: "embed_domains")', function() {
      // uncomment below and update the code to test the property embedDomains
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property encryptPdfsPassword (base name: "encrypt_pdfs_password")', function() {
      // uncomment below and update the code to test the property encryptPdfsPassword
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property encryptPdfs (base name: "encrypt_pdfs")', function() {
      // uncomment below and update the code to test the property encryptPdfs
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property expirationInterval (base name: "expiration_interval")', function() {
      // uncomment below and update the code to test the property expirationInterval
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property expireAfter (base name: "expire_after")', function() {
      // uncomment below and update the code to test the property expireAfter
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property expireSubmissions (base name: "expire_submissions")', function() {
      // uncomment below and update the code to test the property expireSubmissions
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property externalPredefinedFieldsTemplateId (base name: "external_predefined_fields_template_id")', function() {
      // uncomment below and update the code to test the property externalPredefinedFieldsTemplateId
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property externalPredefinedFieldsTemplateName (base name: "external_predefined_fields_template_name")', function() {
      // uncomment below and update the code to test the property externalPredefinedFieldsTemplateName
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property firstTemplate (base name: "first_template")', function() {
      // uncomment below and update the code to test the property firstTemplate
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property locked (base name: "locked")', function() {
      // uncomment below and update the code to test the property locked
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property mergeAuditTrailPdf (base name: "merge_audit_trail_pdf")', function() {
      // uncomment below and update the code to test the property mergeAuditTrailPdf
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property pageCount (base name: "page_count")', function() {
      // uncomment below and update the code to test the property pageCount
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property pageDimensions (base name: "page_dimensions")', function() {
      // uncomment below and update the code to test the property pageDimensions
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property parentFolderId (base name: "parent_folder_id")', function() {
      // uncomment below and update the code to test the property parentFolderId
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property permanentDocumentUrl (base name: "permanent_document_url")', function() {
      // uncomment below and update the code to test the property permanentDocumentUrl
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property publicSubmissions (base name: "public_submissions")', function() {
      // uncomment below and update the code to test the property publicSubmissions
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property publicWebForm (base name: "public_web_form")', function() {
      // uncomment below and update the code to test the property publicWebForm
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirect_url")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property slackWebhookUrl (base name: "slack_webhook_url")', function() {
      // uncomment below and update the code to test the property slackWebhookUrl
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property templateType (base name: "template_type")', function() {
      // uncomment below and update the code to test the property templateType
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property versionPublishedAt (base name: "version_published_at")', function() {
      // uncomment below and update the code to test the property versionPublishedAt
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property webhookUrl (base name: "webhook_url")', function() {
      // uncomment below and update the code to test the property webhookUrl
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property demo (base name: "demo")', function() {
      // uncomment below and update the code to test the property demo
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property latestVersion (base name: "latest_version")', function() {
      // uncomment below and update the code to test the property latestVersion
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property lastChangedAt (base name: "last_changed_at")', function() {
      // uncomment below and update the code to test the property lastChangedAt
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property lastChangedByType (base name: "last_changed_by_type")', function() {
      // uncomment below and update the code to test the property lastChangedByType
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

    it('should have the property lastChangedById (base name: "last_changed_by_id")', function() {
      // uncomment below and update the code to test the property lastChangedById
      //var instance = new DocSpring.TemplatePreview();
      //expect(instance).to.be();
    });

  });

}));
