/**
 * DocSpring API
 * DocSpring provides an API that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddFieldsData from './model/AddFieldsData';
import BatchGeneratePdfs201Response from './model/BatchGeneratePdfs201Response';
import CombinePdfsData from './model/CombinePdfsData';
import CombinedSubmission from './model/CombinedSubmission';
import CombinedSubmissionAction from './model/CombinedSubmissionAction';
import CombinedSubmissionData from './model/CombinedSubmissionData';
import CopyTemplateOptions from './model/CopyTemplateOptions';
import CreateCombinedSubmissionResponse from './model/CreateCombinedSubmissionResponse';
import CreateCustomFileData from './model/CreateCustomFileData';
import CreateCustomFileResponse from './model/CreateCustomFileResponse';
import CreateFolderData from './model/CreateFolderData';
import CreateHtmlSubmissionData from './model/CreateHtmlSubmissionData';
import CreateHtmlTemplate from './model/CreateHtmlTemplate';
import CreatePdfSubmissionData from './model/CreatePdfSubmissionData';
import CreatePdfTemplate from './model/CreatePdfTemplate';
import CreateSubmissionDataRequestData from './model/CreateSubmissionDataRequestData';
import CreateSubmissionDataRequestEventRequest from './model/CreateSubmissionDataRequestEventRequest';
import CreateSubmissionDataRequestEventResponse from './model/CreateSubmissionDataRequestEventResponse';
import CreateSubmissionDataRequestResponse from './model/CreateSubmissionDataRequestResponse';
import CreateSubmissionDataRequestTokenResponse from './model/CreateSubmissionDataRequestTokenResponse';
import CreateSubmissionResponse from './model/CreateSubmissionResponse';
import CustomFile from './model/CustomFile';
import ErrorResponse from './model/ErrorResponse';
import Folder from './model/Folder';
import JsonSchema from './model/JsonSchema';
import ListSubmissionsResponse from './model/ListSubmissionsResponse';
import MoveFolderData from './model/MoveFolderData';
import MoveTemplateData from './model/MoveTemplateData';
import MultipleErrorsResponse from './model/MultipleErrorsResponse';
import RenameFolderData from './model/RenameFolderData';
import Submission from './model/Submission';
import SubmissionAction from './model/SubmissionAction';
import SubmissionBatch from './model/SubmissionBatch';
import SubmissionBatchData from './model/SubmissionBatchData';
import SubmissionBatchWithSubmissions from './model/SubmissionBatchWithSubmissions';
import SubmissionDataRequest from './model/SubmissionDataRequest';
import SubmissionDataRequestEvent from './model/SubmissionDataRequestEvent';
import SubmissionDataRequestShow from './model/SubmissionDataRequestShow';
import SubmissionDataRequestToken from './model/SubmissionDataRequestToken';
import SubmissionPreview from './model/SubmissionPreview';
import SuccessErrorResponse from './model/SuccessErrorResponse';
import SuccessMultipleErrorsResponse from './model/SuccessMultipleErrorsResponse';
import Template from './model/Template';
import TemplateAddFieldsResponse from './model/TemplateAddFieldsResponse';
import TemplatePreview from './model/TemplatePreview';
import UpdateHtmlTemplate from './model/UpdateHtmlTemplate';
import UpdateSubmissionDataRequestData from './model/UpdateSubmissionDataRequestData';
import UploadPresignResponse from './model/UploadPresignResponse';
import PDFApi from './api/PDFApi';


/**
* An API client for the DocSpring PDF generation service.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DocSpring = require('index'); // See note below*.
* var xxxSvc = new DocSpring.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DocSpring.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DocSpring.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DocSpring.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddFieldsData model constructor.
     * @property {module:model/AddFieldsData}
     */
    AddFieldsData,

    /**
     * The BatchGeneratePdfs201Response model constructor.
     * @property {module:model/BatchGeneratePdfs201Response}
     */
    BatchGeneratePdfs201Response,

    /**
     * The CombinePdfsData model constructor.
     * @property {module:model/CombinePdfsData}
     */
    CombinePdfsData,

    /**
     * The CombinedSubmission model constructor.
     * @property {module:model/CombinedSubmission}
     */
    CombinedSubmission,

    /**
     * The CombinedSubmissionAction model constructor.
     * @property {module:model/CombinedSubmissionAction}
     */
    CombinedSubmissionAction,

    /**
     * The CombinedSubmissionData model constructor.
     * @property {module:model/CombinedSubmissionData}
     */
    CombinedSubmissionData,

    /**
     * The CopyTemplateOptions model constructor.
     * @property {module:model/CopyTemplateOptions}
     */
    CopyTemplateOptions,

    /**
     * The CreateCombinedSubmissionResponse model constructor.
     * @property {module:model/CreateCombinedSubmissionResponse}
     */
    CreateCombinedSubmissionResponse,

    /**
     * The CreateCustomFileData model constructor.
     * @property {module:model/CreateCustomFileData}
     */
    CreateCustomFileData,

    /**
     * The CreateCustomFileResponse model constructor.
     * @property {module:model/CreateCustomFileResponse}
     */
    CreateCustomFileResponse,

    /**
     * The CreateFolderData model constructor.
     * @property {module:model/CreateFolderData}
     */
    CreateFolderData,

    /**
     * The CreateHtmlSubmissionData model constructor.
     * @property {module:model/CreateHtmlSubmissionData}
     */
    CreateHtmlSubmissionData,

    /**
     * The CreateHtmlTemplate model constructor.
     * @property {module:model/CreateHtmlTemplate}
     */
    CreateHtmlTemplate,

    /**
     * The CreatePdfSubmissionData model constructor.
     * @property {module:model/CreatePdfSubmissionData}
     */
    CreatePdfSubmissionData,

    /**
     * The CreatePdfTemplate model constructor.
     * @property {module:model/CreatePdfTemplate}
     */
    CreatePdfTemplate,

    /**
     * The CreateSubmissionDataRequestData model constructor.
     * @property {module:model/CreateSubmissionDataRequestData}
     */
    CreateSubmissionDataRequestData,

    /**
     * The CreateSubmissionDataRequestEventRequest model constructor.
     * @property {module:model/CreateSubmissionDataRequestEventRequest}
     */
    CreateSubmissionDataRequestEventRequest,

    /**
     * The CreateSubmissionDataRequestEventResponse model constructor.
     * @property {module:model/CreateSubmissionDataRequestEventResponse}
     */
    CreateSubmissionDataRequestEventResponse,

    /**
     * The CreateSubmissionDataRequestResponse model constructor.
     * @property {module:model/CreateSubmissionDataRequestResponse}
     */
    CreateSubmissionDataRequestResponse,

    /**
     * The CreateSubmissionDataRequestTokenResponse model constructor.
     * @property {module:model/CreateSubmissionDataRequestTokenResponse}
     */
    CreateSubmissionDataRequestTokenResponse,

    /**
     * The CreateSubmissionResponse model constructor.
     * @property {module:model/CreateSubmissionResponse}
     */
    CreateSubmissionResponse,

    /**
     * The CustomFile model constructor.
     * @property {module:model/CustomFile}
     */
    CustomFile,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Folder model constructor.
     * @property {module:model/Folder}
     */
    Folder,

    /**
     * The JsonSchema model constructor.
     * @property {module:model/JsonSchema}
     */
    JsonSchema,

    /**
     * The ListSubmissionsResponse model constructor.
     * @property {module:model/ListSubmissionsResponse}
     */
    ListSubmissionsResponse,

    /**
     * The MoveFolderData model constructor.
     * @property {module:model/MoveFolderData}
     */
    MoveFolderData,

    /**
     * The MoveTemplateData model constructor.
     * @property {module:model/MoveTemplateData}
     */
    MoveTemplateData,

    /**
     * The MultipleErrorsResponse model constructor.
     * @property {module:model/MultipleErrorsResponse}
     */
    MultipleErrorsResponse,

    /**
     * The RenameFolderData model constructor.
     * @property {module:model/RenameFolderData}
     */
    RenameFolderData,

    /**
     * The Submission model constructor.
     * @property {module:model/Submission}
     */
    Submission,

    /**
     * The SubmissionAction model constructor.
     * @property {module:model/SubmissionAction}
     */
    SubmissionAction,

    /**
     * The SubmissionBatch model constructor.
     * @property {module:model/SubmissionBatch}
     */
    SubmissionBatch,

    /**
     * The SubmissionBatchData model constructor.
     * @property {module:model/SubmissionBatchData}
     */
    SubmissionBatchData,

    /**
     * The SubmissionBatchWithSubmissions model constructor.
     * @property {module:model/SubmissionBatchWithSubmissions}
     */
    SubmissionBatchWithSubmissions,

    /**
     * The SubmissionDataRequest model constructor.
     * @property {module:model/SubmissionDataRequest}
     */
    SubmissionDataRequest,

    /**
     * The SubmissionDataRequestEvent model constructor.
     * @property {module:model/SubmissionDataRequestEvent}
     */
    SubmissionDataRequestEvent,

    /**
     * The SubmissionDataRequestShow model constructor.
     * @property {module:model/SubmissionDataRequestShow}
     */
    SubmissionDataRequestShow,

    /**
     * The SubmissionDataRequestToken model constructor.
     * @property {module:model/SubmissionDataRequestToken}
     */
    SubmissionDataRequestToken,

    /**
     * The SubmissionPreview model constructor.
     * @property {module:model/SubmissionPreview}
     */
    SubmissionPreview,

    /**
     * The SuccessErrorResponse model constructor.
     * @property {module:model/SuccessErrorResponse}
     */
    SuccessErrorResponse,

    /**
     * The SuccessMultipleErrorsResponse model constructor.
     * @property {module:model/SuccessMultipleErrorsResponse}
     */
    SuccessMultipleErrorsResponse,

    /**
     * The Template model constructor.
     * @property {module:model/Template}
     */
    Template,

    /**
     * The TemplateAddFieldsResponse model constructor.
     * @property {module:model/TemplateAddFieldsResponse}
     */
    TemplateAddFieldsResponse,

    /**
     * The TemplatePreview model constructor.
     * @property {module:model/TemplatePreview}
     */
    TemplatePreview,

    /**
     * The UpdateHtmlTemplate model constructor.
     * @property {module:model/UpdateHtmlTemplate}
     */
    UpdateHtmlTemplate,

    /**
     * The UpdateSubmissionDataRequestData model constructor.
     * @property {module:model/UpdateSubmissionDataRequestData}
     */
    UpdateSubmissionDataRequestData,

    /**
     * The UploadPresignResponse model constructor.
     * @property {module:model/UploadPresignResponse}
     */
    UploadPresignResponse,

    /**
    * The PDFApi service constructor.
    * @property {module:api/PDFApi}
    */
    PDFApi
};
